name: Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Setup Docker (gunakan image Docker yang sesuai)
      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v2

      # Langkah 3: Jalankan pengujian di dalam container Docker
      - name: Run tests in Docker container
        run: |
          docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          openjdk:23-jdk bash -c "chmod +x ./gradlew && ./gradlew clean test"

      # Langkah 4: Simpan artefak hasil pengujian
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
